# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T15:07:56+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity

from models import (
    SkcerCertificatePostRequest,
    SkcerCertificatePostResponse,
    SkcerCertificatePostResponse1,
    SkcerCertificatePostResponse2,
    SkcerCertificatePostResponse3,
    SkcerCertificatePostResponse4,
    SkcerCertificatePostResponse5,
    SkcerCertificatePostResponse6,
    SkmstCertificatePostRequest,
    SkmstCertificatePostResponse,
    SkmstCertificatePostResponse1,
    SkmstCertificatePostResponse2,
    SkmstCertificatePostResponse3,
    SkmstCertificatePostResponse4,
    SkmstCertificatePostResponse5,
    SkmstCertificatePostResponse6,
)

app = MCPProxy(
    description='Certificates and Marksheets of the training conducted by Indian Navy are available to the Officers/ Sailors in their DigiLocker accounts.',
    termsOfService='https://apisetu.gov.in/terms.php',
    title='Indian Navy (INS Valsura)',
    version='3.0.0',
    servers=[{'url': 'https://apisetu.gov.in/insvalsura/v3'}],
)


@app.post(
    '/skcer/certificate',
    description=""" API to verify Skill Certificate. """,
    tags=['certificate_management'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def skcer(body: SkcerCertificatePostRequest = None):
    """
    Skill Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/skmst/certificate',
    description=""" API to verify Skill Marksheet/ Score Card. """,
    tags=['certificate_management'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def skmst(body: SkmstCertificatePostRequest = None):
    """
    Skill Marksheet/ Score Card
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
